config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end

  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  
  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'

  

  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	
	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 140 }
	


end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :microposts, dependent: :destroy
	
	has_many :relationships, foreign_key: "follower_id", dependent: :destroy
	has_many :followed_users, through: :relationships, source: :followed

	has_many :reverse_relationships, foreign_key: "followed_id", 
																		class_name: "Relationship",
																		dependent: :destroy
	has_many :followers, through: :reverse_relationships, source: :follower


	before_save { self.email = email.downcase }
	before_create :create_remember_token

	validates( :name, presence: true, length: { maximum: 50 } )

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates( :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
							uniqueness: { case_sensitive: false } )

	has_secure_password

	validates(:password, length: { minimum: 6 })

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	def feed
		# Preliminary -> Following Users
		Micropost.where("user_id = ?", id)
		#Micropost.from_users_followed_by(self)
	end

	def following?(other_user)
		relationships.find_by(followed_id: other_user.id)
	end

	def follow!(other_user)
		relationships.create!(followed_id: other_user.id)
	end

	def unfollow!(other_user)
		relationships.find_by(followed_id: other_user.id).destroy!
	end

	private
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def index
  end

  def create
  	@micropost = current_user.microposts.build(micropost_params)
  	if @micropost.save
  		flash[:success] = "Campaign created!"
  		redirect_to root_url
  	else
  		@feed_items = []
  		render 'static_pages/home'
  	end
  end

  def destroy
  	@micropost.destroy
  	redirect_to root_url
  end

  private
  	def micropost_params
  		params.require(:micropost).permit(:content)
  	end

  	def correct_user
  		@micropost = current_user.microposts.find_by(id: params[:id])
  		redirect_to root_url if @micropost.nil?
  	end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :signed_in_user

	def create
		@user = User.find(params[:relationship][:followed_id])
		current_user.follow!(@user)
		#redirect_to @user
		respond_to do |format|
			format.html { redirect_to @user }
			format.js
		end
	end

	def destroy
		@user = Relationship.find(params[:id]).followed
		current_user.unfollow!(@user)
		#redirect_to @user
		respond_to do |format|
			format.html { redirect_to @user }
			format.js
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
		respond_to do |format|
			format.html
			format.js
		end
		@msg = "We are together!"
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			# Sign the user in and redirect to his show page
			sign_in user
			#redirect_back_or user
			redirect_to root_url
		else
			# Create an eror msg and re-render the signin form
			flash.now[:error] = 'Invalid email/password combination' # not quite right!
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@title = "Home"
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  	@title = "Help"
  end

  def about
  	@title = "About"
  end

  def logon
  	@title = "LogOn"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :signed_in_user, 
                only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		# handle success
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle success upd
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def index
    @users = User.paginate(:page => params[:page], per_page: 5)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
    	params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # before filters
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def signed_in?
		!current_user.nil?
	end

	# Create a assignment
	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

	# Friendly redirects
	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for a given user
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", "#" %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>

app/views/layouts/_navbar.html.erb
  <div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-target="navbar-responsive-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand"> All4One &nbsp;
         <%= image_tag("svg/bee-margot.svg") %>
        </a>  
        <div class="nav-collapse collapse navbar-responsive-collapse">
          <ul class="nav">
            <li>
              <a class="link-navbar" href="/home"> 
                Home
              </a>
            </li>
          </ul>

          <ul class="nav pull-right">
            <% if !signed_in? %>
            <li>
              <%= link_to "<i class='icon-user'></i>".html_safe, new_session_path, { :remote => true, "data-toggle" => "modal", "data-target" => "#modal-signin" } %>
            </li>
            <% end %>
            <li>
              <a href="#"> 
                <%= image_tag("social/32/facebook.png") %>
              </a>
            </li>
            <li>
              <a href="#">
                <%= image_tag("social/32/twitter.png") %>
              </a>
            </li>
            <li>
              <a href="#"> 
                <%= image_tag("social/32/linkedin.png") %>
              </a>
            </li>

            <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-cog"></i></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
              </ul>
            </li>
            <% end %>
          </ul>

        </div>
      </div>
    </div>
  </div>

<div id="modal-signin" class="modal hide fade" role="dialog">
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_signin_form.html.erb
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Sign In</h3>
  </div>
  <div class="modal-body">
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="container-fluid span10 offset1">
          <h4>User Info</h4>
          <div class="control-group">
            
            <%= form_for(:session, url: sessions_path) do |f| %>

              <%= f.label :email %>
              <%= f.text_field :email %>

              <%= f.label :password %>
              <%= f.password_field :password %>

              <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
            <% end %>

            <p>New user? <%= link_to "Create an account", signup_path %></p>
            
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample Rails App - <%= @title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid">
    <%= render 'layouts/navbar' %>
  </div>
  <div class="container-fluid">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %>
    <%= link_to "delete", micropost, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micropost.content %>
  <% end %>
</li>

app/views/relationships/create.js.erb
$('#follow_form').html("<%= escape_javascript(render('users/unfollow')) %>")
$('#followers').html("<%= @user.followers.count %>")

app/views/relationships/destroy.js.erb
$('#follow_form').html("<%= escape_javascript(render('users/follow')) %>")
$('#followers').html("<%= @user.followers.count %>")

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p>This is the About Us of Sample App for sure!</p>

<!-- Button to trigger modal -->
<a href="#myModal" role="button" class="btn" data-toggle="modal">Launch demo modal</a>
 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>Sample App Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>
<p>as I am the Sample App Help page</p>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span8">
			<div class="form-horizontal">
				<input type="text">
				<a class="btn btn-small btn-primary" href="#">Button</a>
			</div>
		</div>
		<div class="span4">
		<p>dflkjhskldjhfsdg
			sdgsdgsdgsd asdg sdg sdgsdfg sg 
		 sg sdfgsf gsfg sfgsdfg dfg fdg sdfg 
		 asdfg sfdg sfg sfg sfg 
		 s gsfd gsfg sfg fg 
		 fsdg sdfg sfg asfg sdfg sgsdg sdfgsg 
		 sdf gsdg sdg sdfg sdfh sdfh fdh fdh df
		 h sfdh dfh dfh dfsh fdh fd h
		 dfh gfhg sdfh fh sfh sdfh dfh dfh 
		</p>
		<table class="table table-condensed">
			<thead>
				<th>Nome</th>
				<th>Descrição</th>
			</thead>
			<tbody>
				<tr>
					<td>Coisas</td>
					<td>Diversas variãções aleatórias</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">
    	<h3>Campaigns History</h3>
    	<%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>All4One - caring for people in need</h1>

    <h2>
      We are the All4One crew - join us to make a better world.
    </h2>

    <%= link_to "Sign up now!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>

<% end %>

app/views/static_pages/logon.html.erb
<div id="signin" class="modal hide fade" role="dialog">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Sign In</h3>
  </div>
  <div class="modal-body">
		<div class="container-fluid">
			<div class="row-fluid">
				<div class="container-fluid span10 offset1">
					<h4>User Info</h4>
					<div class="control-group">
						
						<input class="span12" type="text" id="user_name" placeholder="username"/>
						<input class="span12" type="password" id="user_pass" placeholder="password"/>
						<br><br>
						<a class="btn btn-small btn-primary" href="#">Sign In</a>
						<br><br>
						<a href="#">Forgot password</a>
						<a class="btn btn-small btn-success pull-right" href="">Create Account</a>
					</div>
				</div>
			</div>
		</div>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), 
							remote: true) do |f| %>
	<div><%= f.hidden_field :followed_id  %></div>
	<%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user), 
			html: {method: :delete},
			remote: true) do |f| %>
	<%= f.submit "Unfollow", class: "btn btn-large" %>

<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  	| <%= link_to "<i class='icon-trash'></i>".html_safe, user, method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<h1>All users listing</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="row-fluid">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row-fluid">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>

  <div class="span8">
    <%= render 'follow_form' if signed_in? %>
  	<% if @user.microposts.any? %>
  		<h3>Campaigns (<%= @user.microposts.count %>)</h3><%= will_paginate @microposts %>
  		<ol class="microposts">
  			<%= render @microposts %>
  		</ol>
  		<%= will_paginate @microposts %>
  	<% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user, title: user.name %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>